apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volume-claim-gce
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi

